spring:
  profiles:
    active: local

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



